### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by safinmansur20201** [KiuviGonka/Easy_fish#1]
Your discord name and tag doesn't exist as Can't send friend request. I have some inquiries. Hopefully you can update the discord or some other method of communication.

**Comment by KiuviGonka** [comment]
contact me on klein#4545

**Comment by safinmansur20201** [comment]
Gives an error. Can't add you. Seems like won't be able to communicate. It's ok if its hard for you. Just wanted to know the price.
